Update XMLConfigParserTest.java to use getQuiesceTimeoutMillis API
NoClassDefFoundError - com.ibm.wsspi.kernel.service.utils.PathUtils

Add Require-Bundle to com.ibm.ws.kernel.feature bnd.bnd