Issue 18669: Add concurrency test testEJBAnnoManagedThreadFactoryInitialization.
This test is intended to prevent regression of the issue outlined below. If Liberty is not matching on resource factories, this test itself doesn't fail, but it triggers intermittent failures in other tests.

AppDefinedResourceFactory for Concurrency 3.0 resource definitions is accidentally matching some very similar services which aren't resource factories, resulting in an intermittent ClassCastException, such as

java.lang.ClassCastException: com.ibm.ws.concurrent.internal.ManagedThreadFactoryService$ManagedThreadFactoryImpl