Also catch IllegalArgumentException in FileUtils.getFile(URL)
As of IBM JDK 8.0 SR4, calling new java.io.File(String) wtih a path to a
URI that corresponds to an archive in an archive, the following
IllegalArgumentException is throw:

  java.lang.IllegalArgumentException: URI is not hierarchical
    at java.io.File.<init>(File.java:429)

To resolve this, we simply do not convert the URL to a URI before getting
the string path and let the JDK handle the conversion.