MyFaces used by jsfContainer_fat_2.3 requires JAXB.
This PR resolves the following error:
Caused by: java.lang.NoClassDefFoundError: javax.xml.bind.DatatypeConverter
	at org.apache.myfaces.application.viewstate.RandomKeyFactory.encode(RandomKeyFactory.java:91)
	at org.apache.myfaces.application.viewstate.RandomKeyFactory.encode(RandomKeyFactory.java:33)
	at org.apache.myfaces.application.viewstate.ServerSideStateCacheImpl.encodeSerializedState(ServerSideStateCacheImpl.java:660)
	at org.apache.myfaces.renderkit.html.HtmlResponseStateManager.writeState(HtmlResponseStateManager.java:83)
	at org.apache.myfaces.application.StateManagerImpl.writeState(StateManagerImpl.java:390)
	at org.apache.myfaces.application.ViewHandlerImpl.writeState(ViewHandlerImpl.java:374)
	at javax.faces.application.ViewHandlerWrapper.writeState(ViewHandlerWrapper.java:79)
	at org.apache.myfaces.shared.renderkit.html.HtmlFormRendererBase.renderViewStateAndHiddenFields(HtmlFormRendererBase.java:241)
	at org.apache.myfaces.shared.renderkit.html.HtmlFormRendererBase.encodeEnd(HtmlFormRendererBase.java:213)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:555)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551)
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1897)
	at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:315)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:117)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:266)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:206)
	... 24 more