Allow EJBContext implementation to be loaded without java.security.Identity present in the runtime JRE: Prevent java.security.Identity from being loaded in getCallerPrincipal(), introduce a ServiceFactory to load EJBSecurityCollaboratorImpl since introspecting this class via reflection will case NoCLassDefFoundError on a JRE without the java.security.Identity class.