Grant Hazelcast library PropertyPermission for Java 2 Security
The Hazelcast CachingProvider static initializer needs to read
hazelcast.* system properties. Under Java 2 Security, this requires
explicit PropertyPermission scoped to the Hazelcast library codebase.

Without this permission, tests fail with:
java.security.AccessControlException: Access denied
(java.util.PropertyPermission hazelcast.logging.class read)

Added javaPermission for hazelcast.* properties to all server configs
that use the HazelcastLib library.